### ISSUE TITLE
Update to Reflect Kana SVG Changes in animCJK

### ISSUE THREAD

**Issue by CalculusAce** [ailectra/kana-json#2]
I wanted to see if you could update your SVG repo to include the additional Kana characters currently supported in animCJK? I noticed in my testing that the small versions in the あ行 (ぁぃぅぇぉ, ァィゥェォ) are missing for the hiragana and katakana sets, even though they currently exist in animCJK. While I recognize there is no stroke difference between the full-sized versions of those characters, it is problematic that they aren't supported for the project I am working on. I would recommend doing a new pull of all the characters in the kana from animCJK, since some other character diagrams have been updated as well.

Thank you for setting up an easy way to use the animCJK diagrams in Hanzi Writer. I hope you can address this soon.

**Comment by ailectra** [comment]
I added the missing small kanas and updated the strokes.

**Comment by CalculusAce** [comment]
Thanks for adding those! If I try to import it from the url provided in the readme (seen below), I am still unable render those characters. Do you still have to recommit the data to get those characters to render via the url import?

https://cdn.jsdelivr.net/gh/ailectra/kana-json@v0.0.1/data
